[versions]
minecraft     = "1.21.8"
fabric-loader = "0.16.14"
parchment     = "1.21.6:2025.06.29"
fabric-api    = "0.129.0+1.21.8"
fabric-kotlin = "1.13.4+kotlin.2.2.0"
arcade        = "0.6.0-beta.53+1.21.8"
placeholder   = "2.7.1+1.21.6"
predicate     = "0.6.0+1.21.2"
permissions   = "0.4.0"

# Plugins
fabric-loom   = "1.11-SNAPSHOT"
mod-publish   = "0.8.4"

[libraries]
minecraft              = { module = "com.mojang:minecraft"                         , version.ref = "minecraft" }
fabric-loader          = { module = "net.fabricmc:fabric-loader"                   , version.ref = "fabric-loader" }
fabric-api             = { module = "net.fabricmc.fabric-api:fabric-api"           , version.ref = "fabric-api" }
fabric-kotlin          = { module = "net.fabricmc:fabric-language-kotlin"          , version.ref = "fabric-kotlin" }
permissions            = { module = "me.lucko:fabric-permissions-api"              , version.ref = "permissions" }
placeholder            = { module = "eu.pb4:placeholder-api"                       , version.ref = "placeholder" }
predicate              = { module = "eu.pb4:predicate-api"                         , version.ref = "predicate" }
arcade-nametags        = { module = "net.casualchampionships:arcade-nametags"      , version.ref = "arcade" }
arcade-commands        = { module = "net.casualchampionships:arcade-commands"      , version.ref = "arcade" }
arcade-event-registry  = { module = "net.casualchampionships:arcade-event-registry", version.ref = "arcade" }
arcade-events-server   = { module = "net.casualchampionships:arcade-events-server" , version.ref = "arcade" }
arcade-extensions      = { module = "net.casualchampionships:arcade-extensions"    , version.ref = "arcade" }
arcade-utils           = { module = "net.casualchampionships:arcade-utils"         , version.ref = "arcade" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }