[versions]
minecraft     = "26.2"
fabric-loader = "0.19.3"
fabric-api    = "0.152.1+26.2"
fabric-kotlin = "1.13.12+kotlin.2.4.0"
arcade        = "0.13.0-beta.6+26.2"
placeholder   = "3.1.0-beta.1+26.2"
predicate     = "0.9.0+26.2"

# Testing
puppets       = "1.7.1+26.2"

# Plugins
fabric-loom   = "1.17-SNAPSHOT"
mod-publish   = "2.1.1"

[libraries]
minecraft               = { module = "com.mojang:minecraft"                           , version.ref = "minecraft" }
fabric-loader           = { module = "net.fabricmc:fabric-loader"                     , version.ref = "fabric-loader" }
fabric-api              = { module = "net.fabricmc.fabric-api:fabric-api"             , version.ref = "fabric-api" }
fabric-kotlin           = { module = "net.fabricmc:fabric-language-kotlin"            , version.ref = "fabric-kotlin" }
placeholder             = { module = "eu.pb4:placeholder-api"                         , version.ref = "placeholder" }
predicate               = { module = "eu.pb4:predicate-api"                           , version.ref = "predicate" }
arcade-nametags         = { module = "net.casualchampionships:arcade-nametags"        , version.ref = "arcade" }
arcade-commands         = { module = "net.casualchampionships:arcade-commands"        , version.ref = "arcade" }
arcade-event-registry   = { module = "net.casualchampionships:arcade-event-registry"  , version.ref = "arcade" }
arcade-events-server    = { module = "net.casualchampionships:arcade-events-server"   , version.ref = "arcade" }
arcade-extensions       = { module = "net.casualchampionships:arcade-extensions"      , version.ref = "arcade" }
arcade-utils            = { module = "net.casualchampionships:arcade-utils"           , version.ref = "arcade" }
arcade-virtual-entities = { module = "net.casualchampionships:arcade-virtual-entities", version.ref = "arcade" }
arcade-observers        = { module = "net.casualchampionships:arcade-observers"       , version.ref = "arcade" }

# Testing
puppets = { module = "me.senseiwells:puppet-players", version.ref = "puppets" }

[bundles]
arcade = ["arcade-nametags", "arcade-commands", "arcade-event-registry", "arcade-events-server", "arcade-extensions", "arcade-utils", "arcade-virtual-entities", "arcade-observers"]

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom"       , version.ref = "fabric-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }